import Head from 'next/head'
import styles from './styles.module.css'

export const Layout = ({children}) => {
  return <div className={styles.container}>
  <Head>
    <title>Buy Me A Coffee</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <main className={styles.main}>
    <h1 className={styles.title}>Buy WiFo A Coffee!</h1>
    {children}
  </main>

  <footer className={styles.footer}>
    <p>Created by @WiFo for Alchemy&apos;s Road to Web3 lesson two!</p>
  </footer>
</div>
}